{"name": "密码缺失", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <TestPytest.TestAllure.test_feature_1.TestLogin object at 0x1047e10b8>\n\n    @allure.story(\"密码缺失\")\n    @allure.title(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_1.py:54: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1622170593036, "stop": 1622170593036}, {"name": "点击密码", "status": "passed", "start": 1622170593036, "stop": 1622170593036}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"/Users/xmly/Documents/workspace/HogwartsSDET17/TestPytest/TestAllure/test_feature_1.py\", line 54, in test_login_failure\n    assert \"1\" == 1\n"}, "start": 1622170593036, "stop": 1622170593037}], "attachments": [{"name": "stdout", "source": "04b44bf6-46c6-4bb2-89e4-ba2d781766fa-attachment.txt", "type": "text/plain"}], "start": 1622170593036, "stop": 1622170593037, "uuid": "4691a9b1-ed76-479b-a0f8-5f8036e3f34c", "historyId": "d68db1317fb31d8457b718964cfe36ea", "testCaseId": "2acaba1775256acba49201c751e99a9e", "fullName": "test_feature_1.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_1"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "52068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_1"}]}