{"name": "test_order", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"login\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"login\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "start": 1622452439801, "stop": 1622452439801, "uuid": "a1e89ee9-1695-47d8-bce0-6c69fba355cd", "historyId": "23bf1c9e394d9270c14f09851859a197", "testCaseId": "d0c7b7a0481bcffe1a1e17370519d09a", "fullName": "test_fixture_auto_5_2#test_order", "labels": [{"name": "suite", "value": "test_fixture_auto_5_2"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "43568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_auto_5_2"}]}